### ISSUE TITLE
Ionic 6 Rewrite Todo's

### ISSUE THREAD

**Issue by demianh** [rondo-verlag/rondo-app#4]
- [x] Tab Bar in Song Ansicht
- [x] Autoscroll
- [x] Links auf About Seite
- [x] Songtext Page
- [x] Navigation: zum richtigen Song springen
- [x] Richtige Animation bei Pagewechsel
- [x] Noten Page
- [x] Akkorde abspielen
- [x] App Version richtig auslesen und anzeigen auf About Seite
- [x] Keep-Screen-On Plugin
- [x] Persistent Storage
- [x] App Icon & Loading Screen
- [x] Midi Plugin / Songs abspielen
- [x] In-App Purchases
- [ ] Build Prozess vorbereiten
- [x] Folder verschieben
- [x] Github Docs aktualisieren

Low Prio: 
- [ ] Android Splash Screen (grafik, nicht nur logo)
- [ ] iOS Splash Screen 3x Resolution
