### ISSUE TITLE
Release v3 TODO's

### ISSUE THREAD

**Issue by demianh** [rondo-verlag/rondo-app#6]
- [x] Build Prozess vorbereiten
- [x] Android Test Build
- [x] iOS Test Build
- [x] Seitenzahlen Buch 2022
- [x] Android Splash Screen (grafik, nicht nur logo)
- [ ] #8
- [ ] #7
- [ ] #9
- [ ] #10
- [x] Querformat: Es werden zwei Lieder angezeigt
- [x] In-App Purchase Android
- [x] Akkorde sind zu nah (Ludmilla, mova Song Notizen)
- [ ] #11

Nice to have / New Features:

- [ ] #13
- [ ] #20
- [ ] Karussell ohne start und ende (`loop` funktioniert nicht mit `virtual`)
- [ ] #14
- [ ] #15
- [ ] #16
- [ ] #12
